### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by julesmorel** [SmartForest-no/SegmentAnyTree#10]
Thank you for your recent fixes, the inference is now starting.
However it still ends with the following error:

Running the container
Input directory: /home/datascience/tmp_in_folder
Output directory: /home/datascience/tmp_out_folder
Script directory: /home/nibio/mutable-outside-world
Renamed: /home/datascience/tmp_out_folder/input_data/sample_sub01.laz to /home/datascience/tmp_out_folder/input_data/sample_sub01.laz
Processing 1 files...
Processing in utm2local: /home/datascience/tmp_out_folder/input_data/sample_sub01.laz
Saving min values to: /home/datascience/tmp_out_folder/utm2local/sample_sub01_out_min_values.json
Output files are saved in: /home/datascience/tmp_out_folder/utm2local
Clearing: /home/datascience/tmp_out_folder/utm2local/treeinsfused/processed_0.2_test
Path does not exist: /home/datascience/tmp_out_folder/utm2local/treeinsfused/processed_0.2_test
/usr/local/lib/python3.8/dist-packages/wandb/__init__.py:998: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is None and resume is not "must":
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.2.0)/charset_normalizer (2.0.6) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/usr/local/lib/python3.8/dist-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
[2024-11-11 01:07:36,313][torch_points3d.trainer][INFO] - DEVICE : cuda
[2024-11-11 01:07:36,570][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/nibio/mutable-outside-world/model_file/PointGroup-PAPER.pt
Processing...
area_name:
sample_sub01_out.ply
data:
Data(instance_labels=[9383781], pos=[9383781, 3], y=[9383781])
test_data_list:
[[Data(instance_labels=[9383781], pos=[9383781, 3], y=[9383781])]]
[2024-11-11 01:07:37,725][torch_points3d.datasets.segmentation.treeins][INFO] - pre_collate_transform ...
[2024-11-11 01:07:37,726][torch_points3d.datasets.segmentation.treeins][INFO] - Compose([
    SaveOriginalPosId,
    GridSampling3D(grid_size=0.2, quantize_coords=False, mode=last),
])
Done!
test_data_list:
[[Data(instance_labels=[9383781], pos=[9383781, 3], y=[9383781])]]
[2024-11-11 01:07:40,606][torch_points3d.datasets.segmentation.treeins][INFO] - pre_collate_transform ...
[2024-11-11 01:07:40,606][torch_points3d.datasets.segmentation.treeins][INFO] - Compose([
    SaveOriginalPosId,
    GridSampling3D(grid_size=0.2, quantize_coords=False, mode=last),
])
[2024-11-11 01:07:46,299][torch_points3d.applications.minkowski][WARNING] - Minkowski API is deprecated in favor of the SparseConv3d API. It should be a simple drop in replacement (no change to the API).
[2024-11-11 01:07:46,300][torch_points3d.applications.modelfactory][INFO] - The config will be used to build the model
[2024-11-11 01:07:46,403][torch_points3d.applications.minkowski][WARNING] - Minkowski API is deprecated in favor of the SparseConv3d API. It should be a simple drop in replacement (no change to the API).
[2024-11-11 01:07:46,403][torch_points3d.applications.modelfactory][INFO] - The config will be used to build the model
[2024-11-11 01:07:46,452][torch_points3d.applications.minkowski][WARNING] - Minkowski API is deprecated in favor of the SparseConv3d API. It should be a simple drop in replacement (no change to the API).
[2024-11-11 01:07:46,452][torch_points3d.applications.modelfactory][INFO] - The config will be used to build the model
Traceback (most recent call last):
  File "eval.py", line 13, in main
    trainer = Trainer(cfg)
  File "/home/nibio/mutable-outside-world/torch_points3d/trainer.py", line 48, in __init__
    self._initialize_trainer()
  File "/home/nibio/mutable-outside-world/torch_points3d/trainer.py", line 91, in _initialize_trainer
    self._model: BaseModel = self._checkpoint.create_model(
  File "/home/nibio/mutable-outside-world/torch_points3d/metrics/model_checkpoint.py", line 181, in create_model
    model = instantiate_model(OmegaConf.create(run_config), dataset)
  File "/home/nibio/mutable-outside-world/torch_points3d/models/model_factory.py", line 44, in instantiate_model
    model = model_cls(model_config, "dummy", dataset, modellib)
  File "/home/nibio/mutable-outside-world/torch_points3d/models/panoptic/PointGroup3heads.py", line 99, in __init__
    thing_classes = dataset.thing_classes
AttributeError: 'TreeinsFusedDataset' object has no attribute 'thing_classes'

**Comment by julesmorel** [comment]
I just saw this has been fixed in a pull request

**Comment by keillernogueira** [comment]
Hi @julesmorel , I am still facing this issue. Have you done anything else (besides pulling the updated code)?

**Comment by dluks** [comment]
I'm also encountering this issue with the latest commit.

**Comment by keillernogueira** [comment]
So, should we reopen this issue then?

**Comment by dluks** [comment]
Well, I think generally an issue shouldn't be closed until a fix has been merged into main, so I'd vote to re-open. I can confirm that the fix proposed in #9 does appear to address the issue, but another issue arises at the end which may or may not be linked to issue reported here. Meanwhile, I think conversation could be moved to #9.

**Comment by julesmorel** [comment]
Indeed, I might have closed the issue a bit too fast.

On my side, the modifications [torch_points3d/datasets/panoptic/treeins.py](https://github.com/SmartForest-no/SegmentAnyTree/pull/9/files#diff-1cfcc7e50fa8f83b372749413ef84c791c4930f714eafc15c00a708308342350) have solved the issue.
